---
default:
  tags:
  - k8s-mgit-bazel

stages:
  - build
  - test

build:
  stage: build
  script:
    - bazel build --keep_going //...

test:
  stage: test
  script:
    - bazel test --keep_going //...
