---
stages:
  - build
  - test

build:
  stage: build
  script:
    - bazel build --keep_going //...
  tags:
    - mgit
    - bazel

test:
  stage: test
  script:
    - bazel test --keep_going //...
  tags:
    - mgit
    - bazel
